// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-caWXay-kA_vkYhqcUPVto4FzEvbKIps',
    appId: '1:834108486797:android:dedb9eb7a2a14453d29ec4',
    messagingSenderId: '834108486797',
    projectId: 'raise-hope',
    storageBucket: 'raise-hope.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwa8ljrutxf4RBudYlhjHzgM7hDiKCmrc',
    appId: '1:834108486797:ios:486778e2b1ca46c6d29ec4',
    messagingSenderId: '834108486797',
    projectId: 'raise-hope',
    storageBucket: 'raise-hope.appspot.com',
    androidClientId:
        '834108486797-9pu50l6rsbgp9hhfn9qcqptku4thbncf.apps.googleusercontent.com',
    iosClientId:
        '834108486797-n3jq32r2lrooddlmm1rqnq9elb3tf0be.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp',
  );
}
